---
all:
  hosts:
    nexus-01:
      ansible_host: 89.169.171.61
  children:
    nexus:
      hosts:
        nexus-01:   
  vars:
    ansible_python_interpreter: /usr/bin/python3.12
    ansible_connection_type: paramiko
    ansible_user: alex
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519