---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 89.169.137.30
    jenkins-agent-01:
      ansible_host: 89.169.136.151
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection_type: paramiko
    ansible_user: centos