---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_host: 192.168.0.100
      ansible_private_key_file: ~/.ssh/id_rsa.pub

vector:
  hosts:
    vector-01:
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_host: 192.168.0.100
      ansible_private_key_file: ~/.ssh/id_rsa.pub