version: '3'

include:
  - proxy.yaml
  
services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    networks:
      backend:
        ipv4_address: 172.20.0.5
    restart: always


  db:
    image: mysql:8
    networks:
      backend:
        ipv4_address: 172.20.0.10
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

